=== irevios/Proyecto-APAM/xml/datos.dtd
<!ELEMENT APAM (plantas, emociones, registros)>
<!ELEMENT plantas (planta+)>
<!ELEMENT planta (temperatura_opt, humedad_aire_opt, humedad_tierra_opt, luminosidad_opt, emocion)>
<!ATTLIST planta
          id CDATA #REQUIRED
          nombre CDATA #REQUIRED>
<!ELEMENT temperatura_opt (#PCDATA)>
<!ATTLIST temperatura_opt
          max CDATA #REQUIRED
          min CDATA #REQUIRED>
<!ELEMENT humedad_aire_opt (#PCDATA)>
<!ATTLIST humedad_aire_opt
          max CDATA #REQUIRED
          min CDATA #REQUIRED>
<!ELEMENT humedad_tierra_opt (#PCDATA)>
<!ATTLIST humedad_tierra_opt
          max CDATA #REQUIRED
          min CDATA #REQUIRED>
<!ELEMENT luminosidad_opt (#PCDATA)>
<!ATTLIST luminosidad_opt
          max CDATA #REQUIRED
          min CDATA #REQUIRED>
<!ELEMENT emocion (#PCDATA)>
<!ATTLIST emocion
          actual CDATA #IMPLIED
          cantidad CDATA #IMPLIED
          id CDATA #IMPLIED
          nombre CDATA #IMPLIED
          rangomax CDATA #IMPLIED
          rangomin CDATA #IMPLIED>
<!ELEMENT emociones (emocion+)>
<!ELEMENT registros (registro+)>
<!ELEMENT registro (temperatura, humedad_aire, humedad_tierra, luminosidad)>
<!ATTLIST registro
          fecha CDATA #REQUIRED
          hora CDATA #REQUIRED
          id CDATA #REQUIRED
          min CDATA #REQUIRED
          planta CDATA #REQUIRED
          seg CDATA #REQUIRED>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT humedad_aire (#PCDATA)>
<!ELEMENT humedad_tierra (#PCDATA)>
<!ELEMENT luminosidad (#PCDATA)>

=== irevios/Proyecto-APAM/xml/datos.xml
<!DOCTYPE APAM SYSTEM "datos.dtd">
<APAM>
	<plantas>
		<planta id="P01" nombre="gardenia">
			<temperatura_opt max="30" min="15"/>
			<humedad_aire_opt max="90" min="40"/>
			<humedad_tierra_opt max="90" min="70"/>
			<luminosidad_opt max="90" min="60"/>
			<emocion cantidad="89" actual="rel"/>
		</planta>
		<planta id="P02" nombre="anturio">
			<temperatura_opt max="25" min="18"/>
			<humedad_aire_opt max="50" min="20"/>
			<humedad_tierra_opt max="80" min="60"/>
			<luminosidad_opt max="70" min="40"/>
			<emocion cantidad="12" actual="pocha"/>
		</planta>
		<planta id="P03" nombre="gardenia">
			<temperatura_opt max="30" min="15"/>
			<humedad_aire_opt max="90" min="40"/>
			<humedad_tierra_opt max="70" min="60"/>
			<luminosidad_opt max="90" min="60"/>
			<emocion cantidad="67" actual="emp"/>
		</planta>
		<planta id="P04" nombre="cactus">
			<temperatura_opt max="45" min="20"/>
			<humedad_aire_opt max="20" min="0"/>
			<humedad_tierra_opt max="30" min="5"/>
			<luminosidad_opt max="100" min="70"/>
			<emocion cantidad="41" actual="enf"/>
		</planta>
	</plantas>
	<emociones>
		<emocion id="fel" nombre="feliz" rangomax="100" rangomin="91"/>
		<emocion id="rel" nombre="relajada" rangomax="90" rangomin="76"/>
		<emocion id="emp" nombre="empachada" rangomax="75" rangomin="61"/>
		<emocion id="est" nombre="estresada" rangomax="60" rangomin="51"/>
		<emocion id="enf" nombre="enfadada" rangomax="50" rangomin="41"/>
		<emocion id="tri" nombre="triste" rangomax="40" rangomin="21"/>
		<emocion id="poc" nombre="pocha" rangomax="20" rangomin="0"/>
	</emociones>
	<registros>
		<registro id="r01" planta="P01" fecha="02/04/2019" hora="12" min="30" seg="23">
			<temperatura>27</temperatura>
			<humedad_aire>62</humedad_aire>
			<humedad_tierra>81</humedad_tierra>
			<luminosidad>73</luminosidad>
		</registro>
		<registro id="r02" planta="P01" fecha="02/04/2019" hora="12" min="40" seg="13">
			<temperatura>27</temperatura>
			<humedad_aire>40</humedad_aire>
			<humedad_tierra>78</humedad_tierra>
			<luminosidad>60</luminosidad>
		</registro>
		<registro id="r03" planta="P01" fecha="02/04/2019" hora="13" min="02" seg="57">
			<temperatura>26</temperatura>
			<humedad_aire>54</humedad_aire>
			<humedad_tierra>76</humedad_tierra>
			<luminosidad>58</luminosidad>
		</registro>
		<registro id="r04" planta="P02" fecha="02/04/2019" hora="12" min="23" seg="23">
			<temperatura>42</temperatura>
			<humedad_aire>0</humedad_aire>
			<humedad_tierra>7</humedad_tierra>
			<luminosidad>68</luminosidad>
		</registro>
		<registro id="r05" planta="P02" fecha="02/04/2019" hora="12" min="40" seg="13">
			<temperatura>27</temperatura>
			<humedad_aire>40</humedad_aire>
			<humedad_tierra>78</humedad_tierra>
			<luminosidad>60</luminosidad>
		</registro>
		<registro id="r06" planta="P02" fecha="02/04/2019" hora="13" min="02" seg="57">
			<temperatura>26</temperatura>
			<humedad_aire>54</humedad_aire>
			<humedad_tierra>76</humedad_tierra>
			<luminosidad>58</luminosidad>
		</registro>
		<registro id="r10" planta="P03" fecha="02/04/2019" hora="12" min="23" seg="23">
			<temperatura>20</temperatura>
			<humedad_aire>96</humedad_aire>
			<humedad_tierra>87</humedad_tierra>
			<luminosidad>72</luminosidad>
		</registro>
		<registro id="r11" planta="P03" fecha="02/04/2019" hora="12" min="40" seg="13">
			<temperatura>27</temperatura>
			<humedad_aire>40</humedad_aire>
			<humedad_tierra>78</humedad_tierra>
			<luminosidad>60</luminosidad>
		</registro>
		<registro id="r12" planta="P03" fecha="02/04/2019" hora="13" min="02" seg="57">
			<temperatura>26</temperatura>
			<humedad_aire>54</humedad_aire>
			<humedad_tierra>76</humedad_tierra>
			<luminosidad>58</luminosidad>
		</registro>
		<registro id="r07" planta="P04" fecha="02/04/2019" hora="12" min="23" seg="23">
			<temperatura>16</temperatura>
			<humedad_aire>28</humedad_aire>
			<humedad_tierra>52</humedad_tierra>
			<luminosidad>85</luminosidad>
		</registro>
		<registro id="r08" planta="P04" fecha="02/04/2019" hora="12" min="40" seg="13">
			<temperatura>27</temperatura>
			<humedad_aire>40</humedad_aire>
			<humedad_tierra>78</humedad_tierra>
			<luminosidad>75</luminosidad>
		</registro>
		<registro id="r09" planta="P04" fecha="02/04/2019" hora="13" min="02" seg="57">
			<temperatura>26</temperatura>
			<humedad_aire>54</humedad_aire>
			<humedad_tierra>76</humedad_tierra>
			<luminosidad>58</luminosidad>
		</registro>
	</registros>
</APAM>
